### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by yanatarkhaeva** [pieromarini/PyNeuNet#1]
Can you please share files that were used to train and test this network? There are a few lines which go
`with open("some_name.CSV")...` and I don't know what format should training or testing data has from this.
Also in main.py: in mnist_train()'s commented lines there is a variable `c` -- what is that standing for? A digit which is now training? But where do we get this `c` from code? And why do we check this way: `if c < 3` to save it into a file?

**Comment by yanatarkhaeva** [comment]
Oh, you know, it seems like I found what you used to train and test your network. But still, can I ask you to explain what you did in lines 31-34 in main.py? Thank you!

**Comment by pieromarini** [comment]
Hello! I [used this](https://pjreddie.com/projects/mnist-in-csv/) for getting the mnist data in the correct format (file is like 100mb so i didnt uploaded, should've left a note).
Those lines are just there for testing purposes, i just wanted to save to file the three first images (just to be sure everything was being loaded correctly).

**Comment by yanatarkhaeva** [comment]
Thank you :3
